export const robots =[
{
id: 1,
name: "antimage",
localized_name: "Anti-Mage",
primary_attr: "Agility",
attack_type: "Melee",
roles: [
" Carry",
" Escape",
" Nuker"
],
img: "/apps/dota2/images/heroes/antimage_full.png?",
icon: "/apps/dota2/images/heroes/antimage_icon.png",
base_health: 200,
base_health_regen: 0.25,
base_mana: 75,
base_mana_regen: 0,
base_armor: -1,
base_mr: 25,
base_attack_min: 29,
base_attack_max: 33,
base_str: 23,
base_agi: 24,
base_int: 12,
str_gain: 1.3,
agi_gain: 3.2,
int_gain: 1.8,
attack_range: 150,
projectile_speed: 0,
attack_rate: 1.4,
move_speed: 310,
turn_rate: 0.5,
cm_enabled: true,
legs: 2,
pro_win: 30,
pro_pick: 63,
hero_id: 1,
pro_ban: 106,
},
{
id: 2,
name: "axe",
localized_name: "Axe",
primary_attr: "Strength",
attack_type: "Melee",
roles: [
" Initiator",
" Durable",
" Disabler",
" Jungler"
],
img: "/apps/dota2/images/heroes/axe_full.png?",
icon: "/apps/dota2/images/heroes/axe_icon.png",
base_health: 200,
base_health_regen: 2.75,
base_mana: 75,
base_mana_regen: 0,
base_armor: -1,
base_mr: 25,
base_attack_min: 27,
base_attack_max: 31,
base_str: 25,
base_agi: 20,
base_int: 18,
str_gain: 3.4,
agi_gain: 2.2,
int_gain: 1.6,
attack_range: 150,
projectile_speed: 900,
attack_rate: 1.7,
move_speed: 295,
turn_rate: 0.6,
cm_enabled: true,
legs: 2,
pro_win: 55,
pro_pick: 122,
hero_id: 2,
pro_ban: 86,

},
{
id: 3,
name: "bane",
localized_name: "Bane",
primary_attr: "Intelligence",
attack_type: "Ranged",
roles: [
" Support",
" Disabler",
" Nuker",
" Durable"
],
img: "/apps/dota2/images/heroes/bane_full.png?",
icon: "/apps/dota2/images/heroes/bane_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: 1,
base_mr: 25,
base_attack_min: 35,
base_attack_max: 41,
base_str: 23,
base_agi: 23,
base_int: 23,
str_gain: 2.6,
agi_gain: 2.6,
int_gain: 2.6,
attack_range: 400,
projectile_speed: 900,
attack_rate: 1.7,
move_speed: 305,
turn_rate: 0.6,
cm_enabled: true,
legs: 4,
pro_win: 44,
pro_pick: 75,
hero_id: 3,
pro_ban: 44,

},
{
id: 4,
name: "bloodseeker",
localized_name: "Bloodseeker",
primary_attr: "Agility",
attack_type: "Melee",
roles: [
" Carry",
" Disabler",
" Jungler",
" Nuker",
" Initiator"
],
img: "/apps/dota2/images/heroes/bloodseeker_full.png?",
icon: "/apps/dota2/images/heroes/bloodseeker_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: 0,
base_mr: 25,
base_attack_min: 33,
base_attack_max: 39,
base_str: 24,
base_agi: 24,
base_int: 18,
str_gain: 2.7,
agi_gain: 3.1,
int_gain: 1.7,
attack_range: 150,
projectile_speed: 900,
attack_rate: 1.7,
move_speed: 295,
turn_rate: 0.5,
cm_enabled: true,
legs: 2,
pro_win: 12,
pro_pick: 24,
hero_id: 4,
pro_ban: 18,

},
{
id: 5,
name: "crystal_maiden",
localized_name: "Crystal Maiden",
primary_attr: "Intelligence",
attack_type: "Ranged",
roles: [
" Support",
" Disabler",
" Nuker",
" Jungler"
],
img: "/apps/dota2/images/heroes/crystal_maiden_full.png?",
icon: "/apps/dota2/images/heroes/crystal_maiden_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: 0,
base_mr: 25,
base_attack_min: 30,
base_attack_max: 36,
base_str: 18,
base_agi: 16,
base_int: 14,
str_gain: 2.2,
agi_gain: 1.6,
int_gain: 3.3,
attack_range: 600,
projectile_speed: 900,
attack_rate: 1.7,
move_speed: 275,
turn_rate: 0.5,
cm_enabled: true,
legs: 2,
pro_win: 119,
pro_pick: 224,
hero_id: 5,
pro_ban: 45,

},
{
id: 6,
name: "drow_ranger",
localized_name: "Drow Ranger",
primary_attr: "Agility",
attack_type: "Ranged",
roles: [
" Carry",
" Disabler",
" Pusher"
],
img: "/apps/dota2/images/heroes/drow_ranger_full.png?",
icon: "/apps/dota2/images/heroes/drow_ranger_icon.png",
base_health: 200,
base_health_regen: 0.25,
base_mana: 75,
base_mana_regen: 0,
base_armor: -3,
base_mr: 25,
base_attack_min: 19,
base_attack_max: 30,
base_str: 17,
base_agi: 29,
base_int: 15,
str_gain: 1.9,
agi_gain: 2.8,
int_gain: 1.4,
attack_range: 625,
projectile_speed: 1250,
attack_rate: 1.7,
move_speed: 285,
turn_rate: 0.7,
cm_enabled: true,
legs: 2,
pro_win: 12,
pro_pick: 20,
hero_id: 6,
pro_ban: 23,

},
{
id: 7,
name: "earthshaker",
localized_name: "Earthshaker",
primary_attr: "Strength",
attack_type: "Melee",
roles: [
" Support",
" Initiator",
" Disabler",
" Nuker"
],
img: "/apps/dota2/images/heroes/earthshaker_full.png?",
icon: "/apps/dota2/images/heroes/earthshaker_icon.png",
base_health: 200,
base_health_regen: 1,
base_mana: 75,
base_mana_regen: 0,
base_armor: 2,
base_mr: 25,
base_attack_min: 27,
base_attack_max: 37,
base_str: 22,
base_agi: 12,
base_int: 16,
str_gain: 3.7,
agi_gain: 1.4,
int_gain: 1.8,
attack_range: 150,
projectile_speed: 0,
attack_rate: 1.7,
move_speed: 310,
turn_rate: 0.9,
cm_enabled: true,
legs: 2,
pro_win: 90,
pro_pick: 206,
hero_id: 7,
pro_ban: 97,

},
{
id: 8,
name: "juggernaut",
localized_name: "Juggernaut",
primary_attr: "Agility",
attack_type: "Melee",
roles: [
" Carry",
" Pusher",
" Escape"
],
img: "/apps/dota2/images/heroes/juggernaut_full.png?",
icon: "/apps/dota2/images/heroes/juggernaut_icon.png",
base_health: 200,
base_health_regen: 0.5,
base_mana: 75,
base_mana_regen: 0,
base_armor: 0,
base_mr: 25,
base_attack_min: 12,
base_attack_max: 16,
base_str: 21,
base_agi: 36,
base_int: 14,
str_gain: 2.2,
agi_gain: 2.8,
int_gain: 1.4,
attack_range: 150,
projectile_speed: 0,
attack_rate: 1.4,
move_speed: 300,
turn_rate: 0.6,
cm_enabled: true,
legs: 2,
pro_win: 109,
pro_pick: 214,
hero_id: 8,
pro_ban: 298,

},
{
id: 9,
name: "mirana",
localized_name: "Mirana",
primary_attr: "Agility",
attack_type: "Ranged",
roles: [
" Carry",
" Support",
" Escape",
" Nuker",
" Disabler"
],
img: "/apps/dota2/images/heroes/mirana_full.png?",
icon: "/apps/dota2/images/heroes/mirana_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: -1,
base_mr: 25,
base_attack_min: 25,
base_attack_max: 30,
base_str: 18,
base_agi: 18,
base_int: 19,
str_gain: 2.2,
agi_gain: 3.7,
int_gain: 1.9,
attack_range: 630,
projectile_speed: 900,
attack_rate: 1.7,
move_speed: 290,
turn_rate: 0.5,
cm_enabled: true,
legs: 2,
pro_win: 125,
pro_pick: 213,
hero_id: 9,
pro_ban: 182,

},
{
id: 10,
name: "morphling",
localized_name: "Morphling",
primary_attr: "Agility",
attack_type: "Ranged",
roles: [
" Carry",
" Escape",
" Durable",
" Nuker",
" Disabler"
],
img: "/apps/dota2/images/heroes/morphling_full.png?",
icon: "/apps/dota2/images/heroes/morphling_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: -2,
base_mr: 25,
base_attack_min: 9,
base_attack_max: 18,
base_str: 20,
base_agi: 24,
base_int: 13,
str_gain: 3,
agi_gain: 4.3,
int_gain: 1.1,
attack_range: 350,
projectile_speed: 1300,
attack_rate: 1.5,
move_speed: 280,
turn_rate: 0.6,
cm_enabled: true,
legs: 0,
pro_win: 41,
pro_pick: 81,
hero_id: 10,
pro_ban: 191,

},
{
id: 11,
name: "nevermore",
localized_name: "Shadow Fiend",
primary_attr: "Agility",
attack_type: "Ranged",
roles: [
" Carry",
" Nuker"
],
img: "/apps/dota2/images/heroes/nevermore_full.png?",
icon: "/apps/dota2/images/heroes/nevermore_icon.png",
base_health: 200,
base_health_regen: 0.25,
base_mana: 75,
base_mana_regen: 0.3,
base_armor: 0,
base_mr: 25,
base_attack_min: 15,
base_attack_max: 21,
base_str: 19,
base_agi: 20,
base_int: 18,
str_gain: 2.5,
agi_gain: 3.5,
int_gain: 2.2,
attack_range: 500,
projectile_speed: 1200,
attack_rate: 1.7,
move_speed: 305,
turn_rate: 1,
cm_enabled: true,
legs: 0,
pro_win: 26,
pro_pick: 47,
hero_id: 11,
pro_ban: 18,

},
{
id: 12,
name: "phantom_lancer",
localized_name: "Phantom Lancer",
primary_attr: "Agility",
attack_type: "Melee",
roles: [
" Carry",
" Escape",
" Pusher",
" Nuker"
],
img: "/apps/dota2/images/heroes/phantom_lancer_full.png?",
icon: "/apps/dota2/images/heroes/phantom_lancer_icon.png",
base_health: 200,
base_health_regen: 1.5,
base_mana: 75,
base_mana_regen: 0,
base_armor: 0,
base_mr: 25,
base_attack_min: 22,
base_attack_max: 44,
base_str: 19,
base_agi: 29,
base_int: 19,
str_gain: 2.2,
agi_gain: 3.2,
int_gain: 2,
attack_range: 150,
projectile_speed: 900,
attack_rate: 1.7,
move_speed: 290,
turn_rate: 0.6,
cm_enabled: true,
legs: 2,
pro_win: 17,
pro_pick: 41,
hero_id: 12,
pro_ban: 46,

},
{
id: 13,
name: "puck",
localized_name: "Puck",
primary_attr: "Intelligence",
attack_type: "Ranged",
roles: [
" Initiator",
" Disabler",
" Escape",
" Nuker"
],
img: "/apps/dota2/images/heroes/puck_full.png?",
icon: "/apps/dota2/images/heroes/puck_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: -1,
base_mr: 25,
base_attack_min: 30,
base_attack_max: 41,
base_str: 17,
base_agi: 22,
base_int: 23,
str_gain: 2.4,
agi_gain: 1.7,
int_gain: 3.5,
attack_range: 550,
projectile_speed: 900,
attack_rate: 1.7,
move_speed: 290,
turn_rate: 0.5,
cm_enabled: true,
legs: 2,
pro_win: 25,
pro_pick: 64,
hero_id: 13,
pro_ban: 49,

},
{
id: 14,
name: "pudge",
localized_name: "Pudge",
primary_attr: "Strength",
attack_type: "Melee",
roles: [
" Disabler",
" Initiator",
" Durable",
" Nuker"
],
img: "/apps/dota2/images/heroes/pudge_full.png?",
icon: "/apps/dota2/images/heroes/pudge_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: -2,
base_mr: 25,
base_attack_min: 40,
base_attack_max: 46,
base_str: 25,
base_agi: 14,
base_int: 16,
str_gain: 4,
agi_gain: 1.5,
int_gain: 1.5,
attack_range: 150,
projectile_speed: 0,
attack_rate: 1.7,
move_speed: 280,
turn_rate: 0.7,
cm_enabled: true,
legs: 2,
pro_win: 37,
pro_pick: 82,
hero_id: 14,
pro_ban: 38,

},
{
id: 15,
name: "razor",
localized_name: "Razor",
primary_attr: "Agility",
attack_type: "Ranged",
roles: [
" Carry",
" Durable",
" Nuker",
" Pusher"
],
img: "/apps/dota2/images/heroes/razor_full.png?",
icon: "/apps/dota2/images/heroes/razor_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: -1,
base_mr: 25,
base_attack_min: 23,
base_attack_max: 25,
base_str: 22,
base_agi: 22,
base_int: 21,
str_gain: 2.6,
agi_gain: 2.1,
int_gain: 1.8,
attack_range: 475,
projectile_speed: 2000,
attack_rate: 1.7,
move_speed: 285,
turn_rate: 0.5,
cm_enabled: true,
legs: 0,
pro_win: 36,
pro_pick: 61,
hero_id: 15,
pro_ban: 83,

},
{
id: 16,
name: "sand_king",
localized_name: "Sand King",
primary_attr: "Strength",
attack_type: "Melee",
roles: [
" Initiator",
" Disabler",
" Support",
" Nuker",
" Escape",
" Jungler"
],
img: "/apps/dota2/images/heroes/sand_king_full.png?",
icon: "/apps/dota2/images/heroes/sand_king_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: -1,
base_mr: 25,
base_attack_min: 23,
base_attack_max: 33,
base_str: 22,
base_agi: 19,
base_int: 19,
str_gain: 3.2,
agi_gain: 1.8,
int_gain: 1.8,
attack_range: 150,
projectile_speed: 900,
attack_rate: 1.7,
move_speed: 290,
turn_rate: 0.5,
cm_enabled: true,
legs: 6,
pro_win: 114,
pro_pick: 220,
hero_id: 16,
pro_ban: 267,

},
{
id: 17,
name: "storm_spirit",
localized_name: "Storm Spirit",
primary_attr: "Intelligence",
attack_type: "Ranged",
roles: [
" Carry",
" Escape",
" Nuker",
" Initiator",
" Disabler"
],
img: "/apps/dota2/images/heroes/storm_spirit_full.png?",
icon: "/apps/dota2/images/heroes/storm_spirit_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: 2,
base_mr: 25,
base_attack_min: 26,
base_attack_max: 36,
base_str: 21,
base_agi: 22,
base_int: 23,
str_gain: 2,
agi_gain: 1.5,
int_gain: 3.9,
attack_range: 480,
projectile_speed: 1100,
attack_rate: 1.7,
move_speed: 285,
turn_rate: 0.8,
cm_enabled: true,
legs: 2,
pro_win: 72,
pro_pick: 138,
hero_id: 17,
pro_ban: 180,

},
{
id: 18,
name: "sven",
localized_name: "Sven",
primary_attr: "Strength",
attack_type: "Melee",
roles: [
" Carry",
" Disabler",
" Initiator",
" Durable",
" Nuker"
],
img: "/apps/dota2/images/heroes/sven_full.png?",
icon: "/apps/dota2/images/heroes/sven_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: 1,
base_mr: 25,
base_attack_min: 43,
base_attack_max: 45,
base_str: 23,
base_agi: 21,
base_int: 16,
str_gain: 3.2,
agi_gain: 2,
int_gain: 1.3,
attack_range: 150,
projectile_speed: 0,
attack_rate: 1.8,
move_speed: 310,
turn_rate: 0.6,
cm_enabled: true,
legs: 2,
pro_win: 69,
pro_pick: 150,
hero_id: 18,
pro_ban: 166,

},
{
id: 19,
name: "tiny",
localized_name: "Tiny",
primary_attr: "Strength",
attack_type: "Melee",
roles: [
" Carry",
" Nuker",
" Pusher",
" Initiator",
" Durable",
" Disabler"
],
img: "/apps/dota2/images/heroes/tiny_full.png?",
icon: "/apps/dota2/images/heroes/tiny_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: 0,
base_mr: 25,
base_attack_min: 44,
base_attack_max: 50,
base_str: 30,
base_agi: 0,
base_int: 17,
str_gain: 4.1,
agi_gain: 0,
int_gain: 2.2,
attack_range: 150,
projectile_speed: 900,
attack_rate: 1.7,
move_speed: 290,
turn_rate: 0.5,
cm_enabled: true,
legs: 2,
pro_win: 221,
pro_pick: 421,
hero_id: 19,
pro_ban: 305,

},
{
id: 20,
name: "vengefulspirit",
localized_name: "Vengeful Spirit",
primary_attr: "Agility",
attack_type: "Ranged",
roles: [
" Support",
" Initiator",
" Disabler",
" Nuker",
" Escape"
],
img: "/apps/dota2/images/heroes/vengefulspirit_full.png?",
icon: "/apps/dota2/images/heroes/vengefulspirit_icon.png",
base_health: 200,
base_health_regen: 0.25,
base_mana: 75,
base_mana_regen: 0,
base_armor: 0,
base_mr: 25,
base_attack_min: 12,
base_attack_max: 20,
base_str: 19,
base_agi: 27,
base_int: 13,
str_gain: 2.9,
agi_gain: 3.8,
int_gain: 1.5,
attack_range: 400,
projectile_speed: 1500,
attack_rate: 1.7,
move_speed: 290,
turn_rate: 0.6,
cm_enabled: true,
legs: 2,
pro_win: 14,
pro_pick: 33,
hero_id: 20,
pro_ban: 1,

},
{
id: 21,
name: "windrunner",
localized_name: "Windranger",
primary_attr: "Intelligence",
attack_type: "Ranged",
roles: [
" Carry",
" Support",
" Disabler",
" Escape",
" Nuker"
],
img: "/apps/dota2/images/heroes/windrunner_full.png?",
icon: "/apps/dota2/images/heroes/windrunner_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: -1,
base_mr: 25,
base_attack_min: 24,
base_attack_max: 36,
base_str: 18,
base_agi: 17,
base_int: 18,
str_gain: 3,
agi_gain: 1.4,
int_gain: 3,
attack_range: 600,
projectile_speed: 1250,
attack_rate: 1.5,
move_speed: 290,
turn_rate: 0.8,
cm_enabled: true,
legs: 2,
pro_win: 69,
pro_pick: 144,
hero_id: 21,
pro_ban: 102,

},
{
id: 22,
name: "zuus",
localized_name: "Zeus",
primary_attr: "Intelligence",
attack_type: "Ranged",
roles: [
" Nuker"
],
img: "/apps/dota2/images/heroes/zuus_full.png?",
icon: "/apps/dota2/images/heroes/zuus_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0.25,
base_armor: 0,
base_mr: 25,
base_attack_min: 33,
base_attack_max: 41,
base_str: 21,
base_agi: 11,
base_int: 21,
str_gain: 2.1,
agi_gain: 1.2,
int_gain: 3.3,
attack_range: 380,
projectile_speed: 1100,
attack_rate: 1.7,
move_speed: 295,
turn_rate: 0.6,
cm_enabled: true,
legs: 2,
pro_win: 32,
pro_pick: 59,
hero_id: 22,
pro_ban: 16,

},
{
id: 23,
name: "kunkka",
localized_name: "Kunkka",
primary_attr: "Strength",
attack_type: "Melee",
roles: [
" Carry",
" Support",
" Disabler",
" Initiator",
" Durable",
" Nuker"
],
img: "/apps/dota2/images/heroes/kunkka_full.png?",
icon: "/apps/dota2/images/heroes/kunkka_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: 1,
base_mr: 25,
base_attack_min: 26,
base_attack_max: 36,
base_str: 24,
base_agi: 14,
base_int: 18,
str_gain: 3.8,
agi_gain: 1.3,
int_gain: 1.5,
attack_range: 150,
projectile_speed: 900,
attack_rate: 1.7,
move_speed: 300,
turn_rate: 0.6,
cm_enabled: true,
legs: 2,
pro_win: 115,
pro_pick: 222,
hero_id: 23,
pro_ban: 317,

},
{
id: 25,
name: "lina",
localized_name: "Lina",
primary_attr: "Intelligence",
attack_type: "Ranged",
roles: [
" Support",
" Carry",
" Nuker",
" Disabler"
],
img: "/apps/dota2/images/heroes/lina_full.png?",
icon: "/apps/dota2/images/heroes/lina_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: 1,
base_mr: 25,
base_attack_min: 21,
base_attack_max: 33,
base_str: 20,
base_agi: 23,
base_int: 30,
str_gain: 2.2,
agi_gain: 1.8,
int_gain: 3.7,
attack_range: 670,
projectile_speed: 1000,
attack_rate: 1.6,
move_speed: 290,
turn_rate: 0.6,
cm_enabled: true,
legs: 2,
pro_win: 122,
pro_pick: 256,
hero_id: 25,
pro_ban: 350,
},
{
id: 26,
name: "lion",
localized_name: "Lion",
primary_attr: "Intelligence",
attack_type: "Ranged",
roles: [
" Support",
" Disabler",
" Nuker",
" Initiator"
],
img: "/apps/dota2/images/heroes/lion_full.png?",
icon: "/apps/dota2/images/heroes/lion_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: -1,
base_mr: 25,
base_attack_min: 29,
base_attack_max: 35,
base_str: 18,
base_agi: 15,
base_int: 18,
str_gain: 2.2,
agi_gain: 1.5,
int_gain: 3.5,
attack_range: 600,
projectile_speed: 900,
attack_rate: 1.7,
move_speed: 290,
turn_rate: 0.5,
cm_enabled: true,
legs: 2,
pro_win: 33,
pro_pick: 79,
hero_id: 26,
pro_ban: 24,
},
{
id: 27,
name: "shadow_shaman",
localized_name: "Shadow Shaman",
primary_attr: "Intelligence",
attack_type: "Ranged",
roles: [
" Support",
" Pusher",
" Disabler",
" Nuker",
" Initiator"
],
img: "/apps/dota2/images/heroes/shadow_shaman_full.png?",
icon: "/apps/dota2/images/heroes/shadow_shaman_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: 1,
base_mr: 25,
base_attack_min: 52,
base_attack_max: 59,
base_str: 23,
base_agi: 16,
base_int: 19,
str_gain: 2.3,
agi_gain: 1.6,
int_gain: 3.5,
attack_range: 400,
projectile_speed: 900,
attack_rate: 1.7,
move_speed: 285,
turn_rate: 0.5,
cm_enabled: true,
legs: 2,
pro_win: 75,
pro_pick: 150,
hero_id: 27,
pro_ban: 73,

},
{
id: 28,
name: "slardar",
localized_name: "Slardar",
primary_attr: "Strength",
attack_type: "Melee",
roles: [
" Carry",
" Durable",
" Initiator",
" Disabler",
" Escape"
],
img: "/apps/dota2/images/heroes/slardar_full.png?",
icon: "/apps/dota2/images/heroes/slardar_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: 3,
base_mr: 25,
base_attack_min: 30,
base_attack_max: 38,
base_str: 21,
base_agi: 17,
base_int: 15,
str_gain: 3.6,
agi_gain: 2.4,
int_gain: 1.5,
attack_range: 150,
projectile_speed: 0,
attack_rate: 1.7,
move_speed: 290,
turn_rate: 0.5,
cm_enabled: true,
legs: 0,
pro_win: 30,
pro_pick: 60,
hero_id: 28,
pro_ban: 22,
},
{
id: 29,
name: "tidehunter",
localized_name: "Tidehunter",
primary_attr: "Strength",
attack_type: "Melee",
roles: [
" Initiator",
" Durable",
" Disabler",
" Nuker"
],
img: "/apps/dota2/images/heroes/tidehunter_full.png?",
icon: "/apps/dota2/images/heroes/tidehunter_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: 0,
base_mr: 25,
base_attack_min: 25,
base_attack_max: 31,
base_str: 22,
base_agi: 15,
base_int: 16,
str_gain: 3.5,
agi_gain: 1.5,
int_gain: 1.7,
attack_range: 150,
projectile_speed: 900,
attack_rate: 1.7,
move_speed: 300,
turn_rate: 0.5,
cm_enabled: true,
legs: 2,
pro_win: 91,
pro_pick: 171,
hero_id: 29,
pro_ban: 144,
},
{
id: 30,
name: "witch_doctor",
localized_name: "Witch Doctor",
primary_attr: "Intelligence",
attack_type: "Ranged",
roles: [
" Support",
" Nuker",
" Disabler"
],
img: "/apps/dota2/images/heroes/witch_doctor_full.png?",
icon: "/apps/dota2/images/heroes/witch_doctor_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: -1,
base_mr: 25,
base_attack_min: 29,
base_attack_max: 39,
base_str: 18,
base_agi: 13,
base_int: 22,
str_gain: 2.3,
agi_gain: 1.4,
int_gain: 3.3,
attack_range: 600,
projectile_speed: 1200,
attack_rate: 1.7,
move_speed: 300,
turn_rate: 0.5,
cm_enabled: true,
legs: 2,
pro_win: 43,
pro_pick: 98,
hero_id: 30,
pro_ban: 24,

},
{
id: 31,
name: "lich",
localized_name: "Lich",
primary_attr: "Intelligence",
attack_type: "Ranged",
roles: [
" Support",
" Nuker"
],
img: "/apps/dota2/images/heroes/lich_full.png?",
icon: "/apps/dota2/images/heroes/lich_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0.75,
base_armor: -1,
base_mr: 25,
base_attack_min: 26,
base_attack_max: 35,
base_str: 20,
base_agi: 15,
base_int: 20,
str_gain: 2.1,
agi_gain: 2,
int_gain: 4.1,
attack_range: 550,
projectile_speed: 900,
attack_rate: 1.7,
move_speed: 295,
turn_rate: 0.5,
cm_enabled: true,
legs: 2,
pro_win: 50,
pro_pick: 108,
hero_id: 31,
pro_ban: 34,

},
{
id: 32,
name: "riki",
localized_name: "Riki",
primary_attr: "Agility",
attack_type: "Melee",
roles: [
" Carry",
" Escape",
" Disabler"
],
img: "/apps/dota2/images/heroes/riki_full.png?",
icon: "/apps/dota2/images/heroes/riki_icon.png",
base_health: 200,
base_health_regen: 3,
base_mana: 75,
base_mana_regen: 0,
base_armor: 1,
base_mr: 25,
base_attack_min: 21,
base_attack_max: 25,
base_str: 18,
base_agi: 30,
base_int: 14,
str_gain: 1.9,
agi_gain: 2.5,
int_gain: 1.3,
attack_range: 150,
projectile_speed: 900,
attack_rate: 1.7,
move_speed: 290,
turn_rate: 0.6,
cm_enabled: true,
legs: 2,
pro_win: 6,
pro_pick: 13,
hero_id: 32,
pro_ban: 9,

},
{
id: 33,
name: "enigma",
localized_name: "Enigma",
primary_attr: "Intelligence",
attack_type: "Ranged",
roles: [
" Disabler",
" Jungler",
" Initiator",
" Pusher"
],
img: "/apps/dota2/images/heroes/enigma_full.png?",
icon: "/apps/dota2/images/heroes/enigma_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: 2,
base_mr: 25,
base_attack_min: 24,
base_attack_max: 30,
base_str: 21,
base_agi: 14,
base_int: 18,
str_gain: 2.5,
agi_gain: 1,
int_gain: 3.9,
attack_range: 500,
projectile_speed: 900,
attack_rate: 1.7,
move_speed: 290,
turn_rate: 0.5,
cm_enabled: true,
legs: 0,
pro_win: 42,
pro_pick: 81,
hero_id: 33,
pro_ban: 201,

},
{
id: 34,
name: "tinker",
localized_name: "Tinker",
primary_attr: "Intelligence",
attack_type: "Ranged",
roles: [
" Carry",
" Nuker",
" Pusher"
],
img: "/apps/dota2/images/heroes/tinker_full.png?",
icon: "/apps/dota2/images/heroes/tinker_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0.25,
base_armor: 2,
base_mr: 25,
base_attack_min: 24,
base_attack_max: 30,
base_str: 17,
base_agi: 13,
base_int: 28,
str_gain: 2.5,
agi_gain: 1.2,
int_gain: 3.3,
attack_range: 500,
projectile_speed: 900,
attack_rate: 1.7,
move_speed: 290,
turn_rate: 0.6,
cm_enabled: true,
legs: 2,
pro_win: 31,
pro_pick: 66,
hero_id: 34,
pro_ban: 129,

},
{
id: 35,
name: "sniper",
localized_name: "Sniper",
primary_attr: "Agility",
attack_type: "Ranged",
roles: [
" Carry",
" Nuker"
],
img: "/apps/dota2/images/heroes/sniper_full.png?",
icon: "/apps/dota2/images/heroes/sniper_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: -1,
base_mr: 25,
base_attack_min: 15,
base_attack_max: 21,
base_str: 19,
base_agi: 21,
base_int: 15,
str_gain: 1.7,
agi_gain: 3.1,
int_gain: 2.6,
attack_range: 550,
projectile_speed: 3000,
attack_rate: 1.7,
move_speed: 285,
turn_rate: 0.7,
cm_enabled: true,
legs: 2,
pro_win: 7,
pro_pick: 19,
hero_id: 35,
pro_ban: 23,

},
{
id: 36,
name: "necrolyte",
localized_name: "Necrophos",
primary_attr: "Intelligence",
attack_type: "Ranged",
roles: [
" Carry",
" Nuker",
" Durable",
" Disabler"
],
img: "/apps/dota2/images/heroes/necrolyte_full.png?",
icon: "/apps/dota2/images/heroes/necrolyte_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: 1,
base_mr: 25,
base_attack_min: 26,
base_attack_max: 30,
base_str: 18,
base_agi: 12,
base_int: 20,
str_gain: 2.8,
agi_gain: 1.3,
int_gain: 2.9,
attack_range: 500,
projectile_speed: 900,
attack_rate: 1.7,
move_speed: 280,
turn_rate: 0.5,
cm_enabled: true,
legs: 2,
pro_win: 26,
pro_pick: 48,
hero_id: 36,
pro_ban: 33,

},
{
id: 37,
name: "warlock",
localized_name: "Warlock",
primary_attr: "Intelligence",
attack_type: "Ranged",
roles: [
" Support",
" Initiator",
" Disabler"
],
img: "/apps/dota2/images/heroes/warlock_full.png?",
icon: "/apps/dota2/images/heroes/warlock_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: 1,
base_mr: 25,
base_attack_min: 24,
base_attack_max: 34,
base_str: 26,
base_agi: 10,
base_int: 25,
str_gain: 3,
agi_gain: 1,
int_gain: 3.1,
attack_range: 600,
projectile_speed: 1200,
attack_rate: 1.7,
move_speed: 290,
turn_rate: 0.5,
cm_enabled: true,
legs: 2,
pro_win: 65,
pro_pick: 142,
hero_id: 37,
pro_ban: 228,

},
{
id: 38,
name: "beastmaster",
localized_name: "Beastmaster",
primary_attr: "Strength",
attack_type: "Melee",
roles: [
" Initiator",
" Disabler",
" Durable",
" Nuker"
],
img: "/apps/dota2/images/heroes/beastmaster_full.png?",
icon: "/apps/dota2/images/heroes/beastmaster_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: -1,
base_mr: 25,
base_attack_min: 41,
base_attack_max: 45,
base_str: 23,
base_agi: 18,
base_int: 16,
str_gain: 2.9,
agi_gain: 1.6,
int_gain: 1.9,
attack_range: 150,
projectile_speed: 0,
attack_rate: 1.7,
move_speed: 305,
turn_rate: 0.5,
cm_enabled: true,
legs: 2,
pro_win: 27,
pro_pick: 54,
hero_id: 38,
pro_ban: 80,

},
{
id: 39,
name: "queenofpain",
localized_name: "Queen of Pain",
primary_attr: "Intelligence",
attack_type: "Ranged",
roles: [
" Carry",
" Nuker",
" Escape"
],
img: "/apps/dota2/images/heroes/queenofpain_full.png?",
icon: "/apps/dota2/images/heroes/queenofpain_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: 0,
base_mr: 25,
base_attack_min: 20,
base_attack_max: 28,
base_str: 18,
base_agi: 22,
base_int: 25,
str_gain: 2.3,
agi_gain: 2.2,
int_gain: 2.9,
attack_range: 550,
projectile_speed: 1500,
attack_rate: 1.5,
move_speed: 290,
turn_rate: 0.5,
cm_enabled: true,
legs: 2,
pro_win: 45,
pro_pick: 94,
hero_id: 39,
pro_ban: 123,

},
{
id: 40,
name: "venomancer",
localized_name: "Venomancer",
primary_attr: "Agility",
attack_type: "Ranged",
roles: [
" Support",
" Nuker",
" Initiator",
" Pusher",
" Disabler"
],
img: "/apps/dota2/images/heroes/venomancer_full.png?",
icon: "/apps/dota2/images/heroes/venomancer_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: 0,
base_mr: 25,
base_attack_min: 16,
base_attack_max: 18,
base_str: 19,
base_agi: 26,
base_int: 19,
str_gain: 2.1,
agi_gain: 3.2,
int_gain: 1.8,
attack_range: 450,
projectile_speed: 900,
attack_rate: 1.7,
move_speed: 275,
turn_rate: 0.5,
cm_enabled: true,
legs: 0,
pro_win: 8,
pro_pick: 23,
hero_id: 40,
pro_ban: 12,
pick: 113,

},
{
id: 41,
name: "faceless_void",
localized_name: "Faceless Void",
primary_attr: "Agility",
attack_type: "Melee",
roles: [
" Carry",
" Initiator",
" Disabler",
" Escape",
" Durable"
],
img: "/apps/dota2/images/heroes/faceless_void_full.png?",
icon: "/apps/dota2/images/heroes/faceless_void_icon.png",
base_health: 200,
base_health_regen: 0.5,
base_mana: 75,
base_mana_regen: 0,
base_armor: 0,
base_mr: 25,
base_attack_min: 33,
base_attack_max: 39,
base_str: 24,
base_agi: 23,
base_int: 15,
str_gain: 2.4,
agi_gain: 3.2,
int_gain: 1.5,
attack_range: 150,
projectile_speed: 900,
attack_rate: 1.7,
move_speed: 300,
turn_rate: 1,
cm_enabled: true,
legs: 2,
pro_win: 106,
pro_pick: 202,
hero_id: 41,
pro_ban: 243,

},
{
id: 42,
name: "skeleton_king",
localized_name: "Wraith King",
primary_attr: "Strength",
attack_type: "Melee",
roles: [
" Carry",
" Support",
" Durable",
" Disabler",
" Initiator"
],
img: "/apps/dota2/images/heroes/skeleton_king_full.png?",
icon: "/apps/dota2/images/heroes/skeleton_king_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: -1,
base_mr: 25,
base_attack_min: 39,
base_attack_max: 41,
base_str: 22,
base_agi: 18,
base_int: 18,
str_gain: 3.2,
agi_gain: 1.7,
int_gain: 1.6,
attack_range: 150,
projectile_speed: 0,
attack_rate: 1.7,
move_speed: 315,
turn_rate: 0.5,
cm_enabled: true,
legs: 2,
pro_win: 81,
pro_pick: 186,
hero_id: 42,
pro_ban: 127,

},
{
id: 43,
name: "death_prophet",
localized_name: "Death Prophet",
primary_attr: "Intelligence",
attack_type: "Ranged",
roles: [
" Carry",
" Pusher",
" Nuker",
" Disabler"
],
img: "/apps/dota2/images/heroes/death_prophet_full.png?",
icon: "/apps/dota2/images/heroes/death_prophet_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: 0,
base_mr: 25,
base_attack_min: 29,
base_attack_max: 41,
base_str: 19,
base_agi: 14,
base_int: 21,
str_gain: 3.1,
agi_gain: 1.4,
int_gain: 3.5,
attack_range: 600,
projectile_speed: 1000,
attack_rate: 1.7,
move_speed: 310,
turn_rate: 0.5,
cm_enabled: true,
legs: 2,
pro_win: 43,
pro_pick: 84,
hero_id: 43,
pro_ban: 98,

},
{
id: 44,
name: "phantom_assassin",
localized_name: "Phantom Assassin",
primary_attr: "Agility",
attack_type: "Melee",
roles: [
" Carry",
" Escape"
],
img: "/apps/dota2/images/heroes/phantom_assassin_full.png?",
icon: "/apps/dota2/images/heroes/phantom_assassin_icon.png",
base_health: 200,
base_health_regen: 0.25,
base_mana: 75,
base_mana_regen: 0,
base_armor: 1,
base_mr: 25,
base_attack_min: 23,
base_attack_max: 25,
base_str: 21,
base_agi: 23,
base_int: 15,
str_gain: 2.2,
agi_gain: 3.4,
int_gain: 1.4,
attack_range: 150,
projectile_speed: 900,
attack_rate: 1.7,
move_speed: 305,
turn_rate: 0.6,
cm_enabled: true,
legs: 2,
pro_win: 30,
pro_pick: 69,
hero_id: 44,
pro_ban: 37,

},
{
id: 45,
name: "pugna",
localized_name: "Pugna",
primary_attr: "Intelligence",
attack_type: "Ranged",
roles: [
" Nuker",
" Pusher"
],
img: "/apps/dota2/images/heroes/pugna_full.png?",
icon: "/apps/dota2/images/heroes/pugna_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0.5,
base_armor: 0,
base_mr: 25,
base_attack_min: 19,
base_attack_max: 27,
base_str: 19,
base_agi: 16,
base_int: 24,
str_gain: 2,
agi_gain: 1.3,
int_gain: 5.2,
attack_range: 630,
projectile_speed: 900,
attack_rate: 1.7,
move_speed: 330,
turn_rate: 0.5,
cm_enabled: true,
legs: 2,
pro_win: 23,
pro_pick: 46,
hero_id: 45,
pro_ban: 72,

},
{
id: 46,
name: "templar_assassin",
localized_name: "Templar Assassin",
primary_attr: "Agility",
attack_type: "Ranged",
roles: [
" Carry",
" Escape"
],
img: "/apps/dota2/images/heroes/templar_assassin_full.png?",
icon: "/apps/dota2/images/heroes/templar_assassin_icon.png",
base_health: 200,
base_health_regen: 0.25,
base_mana: 75,
base_mana_regen: 0,
base_armor: 1,
base_mr: 25,
base_attack_min: 30,
base_attack_max: 36,
base_str: 19,
base_agi: 23,
base_int: 20,
str_gain: 2.4,
agi_gain: 3.2,
int_gain: 2,
attack_range: 140,
projectile_speed: 900,
attack_rate: 1.7,
move_speed: 305,
turn_rate: 0.7,
cm_enabled: true,
legs: 2,
pro_win: 45,
pro_pick: 79,
hero_id: 46,
pro_ban: 101,

},
{
id: 47,
name: "viper",
localized_name: "Viper",
primary_attr: "Agility",
attack_type: "Ranged",
roles: [
" Carry",
" Durable",
" Initiator",
" Disabler"
],
img: "/apps/dota2/images/heroes/viper_full.png?",
icon: "/apps/dota2/images/heroes/viper_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: -2,
base_mr: 25,
base_attack_min: 23,
base_attack_max: 25,
base_str: 21,
base_agi: 21,
base_int: 15,
str_gain: 2.4,
agi_gain: 2.5,
int_gain: 1.8,
attack_range: 575,
projectile_speed: 1200,
attack_rate: 1.7,
move_speed: 275,
turn_rate: 0.5,
cm_enabled: true,
legs: 0,
pro_win: 18,
pro_pick: 42,
hero_id: 47,
pro_ban: 57,

},
{
id: 48,
name: "luna",
localized_name: "Luna",
primary_attr: "Agility",
attack_type: "Ranged",
roles: [
" Carry",
" Nuker",
" Pusher"
],
img: "/apps/dota2/images/heroes/luna_full.png?",
icon: "/apps/dota2/images/heroes/luna_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: 0,
base_mr: 25,
base_attack_min: 24,
base_attack_max: 30,
base_str: 16,
base_agi: 18,
base_int: 16,
str_gain: 2.2,
agi_gain: 3.6,
int_gain: 1.9,
attack_range: 330,
projectile_speed: 900,
attack_rate: 1.7,
move_speed: 325,
turn_rate: 0.6,
cm_enabled: true,
legs: 2,
pro_win: 4,
pro_pick: 14,
hero_id: 48,
pro_ban: 3,

},
{
id: 49,
name: "dragon_knight",
localized_name: "Dragon Knight",
primary_attr: "Strength",
attack_type: "Melee",
roles: [
" Carry",
" Pusher",
" Durable",
" Disabler",
" Initiator",
" Nuker"
],
img: "/apps/dota2/images/heroes/dragon_knight_full.png?",
icon: "/apps/dota2/images/heroes/dragon_knight_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: 0,
base_mr: 25,
base_attack_min: 31,
base_attack_max: 37,
base_str: 19,
base_agi: 19,
base_int: 15,
str_gain: 3.6,
agi_gain: 2,
int_gain: 1.7,
attack_range: 150,
projectile_speed: 900,
attack_rate: 1.7,
move_speed: 295,
turn_rate: 0.6,
cm_enabled: true,
legs: 2,
pro_win: 35,
pro_pick: 67,
hero_id: 49,
pro_ban: 25,

},
{
id: 50,
name: "dazzle",
localized_name: "Dazzle",
primary_attr: "Intelligence",
attack_type: "Ranged",
roles: [
" Support",
" Nuker",
" Disabler"
],
img: "/apps/dota2/images/heroes/dazzle_full.png?",
icon: "/apps/dota2/images/heroes/dazzle_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: -1,
base_mr: 25,
base_attack_min: 22,
base_attack_max: 28,
base_str: 18,
base_agi: 21,
base_int: 25,
str_gain: 2.5,
agi_gain: 1.7,
int_gain: 3.7,
attack_range: 550,
projectile_speed: 1200,
attack_rate: 1.7,
move_speed: 305,
turn_rate: 0.6,
cm_enabled: true,
legs: 2,
pro_win: 45,
pro_pick: 80,
hero_id: 50,
pro_ban: 79,

},
{
id: 51,
name: "rattletrap",
localized_name: "Clockwerk",
primary_attr: "Strength",
attack_type: "Melee",
roles: [
" Initiator",
" Disabler",
" Durable",
" Nuker"
],
img: "/apps/dota2/images/heroes/rattletrap_full.png?",
icon: "/apps/dota2/images/heroes/rattletrap_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: 0,
base_mr: 25,
base_attack_min: 24,
base_attack_max: 26,
base_str: 26,
base_agi: 13,
base_int: 17,
str_gain: 3.7,
agi_gain: 2.3,
int_gain: 1.3,
attack_range: 150,
projectile_speed: 900,
attack_rate: 1.7,
move_speed: 310,
turn_rate: 0.6,
cm_enabled: true,
legs: 2,
pro_win: 16,
pro_pick: 31,
hero_id: 51,
pro_ban: 7,

},
{
id: 52,
name: "leshrac",
localized_name: "Leshrac",
primary_attr: "Intelligence",
attack_type: "Ranged",
roles: [
" Carry",
" Support",
" Nuker",
" Pusher",
" Disabler"
],
img: "/apps/dota2/images/heroes/leshrac_full.png?",
icon: "/apps/dota2/images/heroes/leshrac_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: 0,
base_mr: 25,
base_attack_min: 19,
base_attack_max: 23,
base_str: 18,
base_agi: 23,
base_int: 22,
str_gain: 2.3,
agi_gain: 2.3,
int_gain: 3.5,
attack_range: 600,
projectile_speed: 900,
attack_rate: 1.7,
move_speed: 325,
turn_rate: 0.5,
cm_enabled: true,
legs: 4,
pro_win: 160,
pro_pick: 316,
hero_id: 52,
pro_ban: 282,

},
{
id: 53,
name: "furion",
localized_name: "Nature's Prophet",
primary_attr: "Intelligence",
attack_type: "Ranged",
roles: [
" Carry",
" Jungler",
" Pusher",
" Escape",
" Nuker"
],
img: "/apps/dota2/images/heroes/furion_full.png?",
icon: "/apps/dota2/images/heroes/furion_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: 2,
base_mr: 25,
base_attack_min: 27,
base_attack_max: 41,
base_str: 21,
base_agi: 18,
base_int: 23,
str_gain: 2.6,
agi_gain: 3.3,
int_gain: 3.3,
attack_range: 600,
projectile_speed: 1125,
attack_rate: 1.7,
move_speed: 290,
turn_rate: 0.6,
cm_enabled: true,
legs: 2,
pro_win: 26,
pro_pick: 44,
hero_id: 53,
pro_ban: 38,

},
{
id: 54,
name: "life_stealer",
localized_name: "Lifestealer",
primary_attr: "Strength",
attack_type: "Melee",
roles: [
" Carry",
" Durable",
" Jungler",
" Escape",
" Disabler"
],
img: "/apps/dota2/images/heroes/life_stealer_full.png?",
icon: "/apps/dota2/images/heroes/life_stealer_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: 0,
base_mr: 25,
base_attack_min: 27,
base_attack_max: 37,
base_str: 25,
base_agi: 18,
base_int: 15,
str_gain: 2.9,
agi_gain: 2.4,
int_gain: 1.8,
attack_range: 150,
projectile_speed: 900,
attack_rate: 1.85,
move_speed: 325,
turn_rate: 1,
cm_enabled: true,
legs: 2,
pro_win: 103,
pro_pick: 208,
hero_id: 54,
pro_ban: 391,

},
{
id: 55,
name: "dark_seer",
localized_name: "Dark Seer",
primary_attr: "Intelligence",
attack_type: "Melee",
roles: [
" Initiator",
" Jungler",
" Escape",
" Disabler"
],
img: "/apps/dota2/images/heroes/dark_seer_full.png?",
icon: "/apps/dota2/images/heroes/dark_seer_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: 3,
base_mr: 25,
base_attack_min: 33,
base_attack_max: 39,
base_str: 21,
base_agi: 12,
base_int: 21,
str_gain: 3.1,
agi_gain: 1.8,
int_gain: 3.1,
attack_range: 150,
projectile_speed: 900,
attack_rate: 1.7,
move_speed: 300,
turn_rate: 0.6,
cm_enabled: true,
legs: 2,
pro_win: 19,
pro_pick: 35,
hero_id: 55,
pro_ban: 58,

},
{
id: 56,
name: "clinkz",
localized_name: "Clinkz",
primary_attr: "Agility",
attack_type: "Ranged",
roles: [
" Carry",
" Escape",
" Pusher"
],
img: "/apps/dota2/images/heroes/clinkz_full.png?",
icon: "/apps/dota2/images/heroes/clinkz_icon.png",
base_health: 200,
base_health_regen: 0.25,
base_mana: 75,
base_mana_regen: 0.25,
base_armor: 0,
base_mr: 25,
base_attack_min: 15,
base_attack_max: 21,
base_str: 12,
base_agi: 22,
base_int: 18,
str_gain: 1.9,
agi_gain: 3,
int_gain: 1.7,
attack_range: 650,
projectile_speed: 900,
attack_rate: 1.7,
move_speed: 290,
turn_rate: 0.5,
cm_enabled: true,
legs: 2,
pro_win: 5,
pro_pick: 16,
hero_id: 56,
pro_ban: 11,

},
{
id: 57,
name: "omniknight",
localized_name: "Omniknight",
primary_attr: "Strength",
attack_type: "Melee",
roles: [
" Support",
" Durable",
" Nuker"
],
img: "/apps/dota2/images/heroes/omniknight_full.png?",
icon: "/apps/dota2/images/heroes/omniknight_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: 2,
base_mr: 25,
base_attack_min: 31,
base_attack_max: 41,
base_str: 22,
base_agi: 15,
base_int: 15,
str_gain: 3.6,
agi_gain: 1.8,
int_gain: 1.8,
attack_range: 150,
projectile_speed: 900,
attack_rate: 1.7,
move_speed: 300,
turn_rate: 0.6,
cm_enabled: true,
legs: 2,
pro_win: 49,
pro_pick: 122,
hero_id: 57,
pro_ban: 261,

},
{
id: 58,
name: "enchantress",
localized_name: "Enchantress",
primary_attr: "Intelligence",
attack_type: "Ranged",
roles: [
" Support",
" Jungler",
" Pusher",
" Durable",
" Disabler"
],
img: "/apps/dota2/images/heroes/enchantress_full.png?",
icon: "/apps/dota2/images/heroes/enchantress_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: 0,
base_mr: 25,
base_attack_min: 30,
base_attack_max: 40,
base_str: 17,
base_agi: 19,
base_int: 19,
str_gain: 1.7,
agi_gain: 1.8,
int_gain: 3.6,
attack_range: 575,
projectile_speed: 900,
attack_rate: 1.7,
move_speed: 315,
turn_rate: 0.5,
cm_enabled: true,
legs: 4,
pro_win: 89,
pro_pick: 160,
hero_id: 58,
pro_ban: 548,

},
{
id: 59,
name: "huskar",
localized_name: "Huskar",
primary_attr: "Strength",
attack_type: "Ranged",
roles: [
" Carry",
" Durable",
" Initiator"
],
img: "/apps/dota2/images/heroes/huskar_full.png?",
icon: "/apps/dota2/images/heroes/huskar_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: -1,
base_mr: 25,
base_attack_min: 19,
base_attack_max: 24,
base_str: 21,
base_agi: 15,
base_int: 18,
str_gain: 3.1,
agi_gain: 1.4,
int_gain: 1.5,
attack_range: 400,
projectile_speed: 1400,
attack_rate: 1.6,
move_speed: 290,
turn_rate: 0.5,
cm_enabled: true,
legs: 2,
pro_win: 12,
pro_pick: 24,
hero_id: 59,
pro_ban: 56,

},
{
id: 60,
name: "night_stalker",
localized_name: "Night Stalker",
primary_attr: "Strength",
attack_type: "Melee",
roles: [
" Carry",
" Initiator",
" Durable",
" Disabler",
" Nuker"
],
img: "/apps/dota2/images/heroes/night_stalker_full.png?",
icon: "/apps/dota2/images/heroes/night_stalker_icon.png",
base_health: 200,
base_health_regen: 1.75,
base_mana: 75,
base_mana_regen: 0,
base_armor: 2,
base_mr: 25,
base_attack_min: 38,
base_attack_max: 42,
base_str: 23,
base_agi: 18,
base_int: 13,
str_gain: 3.2,
agi_gain: 2.3,
int_gain: 1.6,
attack_range: 150,
projectile_speed: 900,
attack_rate: 1.7,
move_speed: 290,
turn_rate: 0.5,
cm_enabled: true,
legs: 2,
pro_win: 23,
pro_pick: 43,
hero_id: 60,
pro_ban: 34,

},
{
id: 61,
name: "broodmother",
localized_name: "Broodmother",
primary_attr: "Agility",
attack_type: "Melee",
roles: [
" Carry",
" Pusher",
" Escape",
" Nuker"
],
img: "/apps/dota2/images/heroes/broodmother_full.png?",
icon: "/apps/dota2/images/heroes/broodmother_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: 0,
base_mr: 25,
base_attack_min: 29,
base_attack_max: 35,
base_str: 18,
base_agi: 15,
base_int: 18,
str_gain: 2.8,
agi_gain: 2.8,
int_gain: 2,
attack_range: 150,
projectile_speed: 900,
attack_rate: 1.7,
move_speed: 275,
turn_rate: 0.5,
cm_enabled: true,
legs: 8,
pro_win: 23,
pro_pick: 48,
hero_id: 61,
pro_ban: 181,

},
{
id: 62,
name: "bounty_hunter",
localized_name: "Bounty Hunter",
primary_attr: "Agility",
attack_type: "Melee",
roles: [
" Escape",
" Nuker"
],
img: "/apps/dota2/images/heroes/bounty_hunter_full.png?",
icon: "/apps/dota2/images/heroes/bounty_hunter_icon.png",
base_health: 200,
base_health_regen: 0.5,
base_mana: 75,
base_mana_regen: 0,
base_armor: 3,
base_mr: 25,
base_attack_min: 24,
base_attack_max: 38,
base_str: 20,
base_agi: 21,
base_int: 19,
str_gain: 2.5,
agi_gain: 2.6,
int_gain: 2,
attack_range: 150,
projectile_speed: 900,
attack_rate: 1.7,
move_speed: 315,
turn_rate: 0.6,
cm_enabled: true,
legs: 2,
pro_win: 16,
pro_pick: 35,
hero_id: 62,
pro_ban: 25,

},
{
id: 63,
name: "weaver",
localized_name: "Weaver",
primary_attr: "Agility",
attack_type: "Ranged",
roles: [
" Carry",
" Escape"
],
img: "/apps/dota2/images/heroes/weaver_full.png?",
icon: "/apps/dota2/images/heroes/weaver_icon.png",
base_health: 200,
base_health_regen: 1,
base_mana: 75,
base_mana_regen: 0.4,
base_armor: -1,
base_mr: 25,
base_attack_min: 36,
base_attack_max: 46,
base_str: 16,
base_agi: 14,
base_int: 13,
str_gain: 1.8,
agi_gain: 3.6,
int_gain: 1.8,
attack_range: 425,
projectile_speed: 900,
attack_rate: 1.8,
move_speed: 275,
turn_rate: 0.5,
cm_enabled: true,
legs: 4,
pro_win: 16,
pro_pick: 37,
hero_id: 63,
pro_ban: 30,

},
{
id: 64,
name: "jakiro",
localized_name: "Jakiro",
primary_attr: "Intelligence",
attack_type: "Ranged",
roles: [
" Support",
" Nuker",
" Pusher",
" Disabler"
],
img: "/apps/dota2/images/heroes/jakiro_full.png?",
icon: "/apps/dota2/images/heroes/jakiro_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: 1,
base_mr: 25,
base_attack_min: 27,
base_attack_max: 35,
base_str: 27,
base_agi: 10,
base_int: 26,
str_gain: 2.8,
agi_gain: 1.2,
int_gain: 3.2,
attack_range: 400,
projectile_speed: 1100,
attack_rate: 1.7,
move_speed: 290,
turn_rate: 0.5,
cm_enabled: true,
legs: 2,
pro_win: 56,
pro_pick: 126,
hero_id: 64,
pro_ban: 31,

},
{
id: 65,
name: "batrider",
localized_name: "Batrider",
primary_attr: "Intelligence",
attack_type: "Ranged",
roles: [
" Initiator",
" Jungler",
" Disabler",
" Escape"
],
img: "/apps/dota2/images/heroes/batrider_full.png?",
icon: "/apps/dota2/images/heroes/batrider_icon.png",
base_health: 200,
base_health_regen: 1.75,
base_mana: 75,
base_mana_regen: 0,
base_armor: 0,
base_mr: 25,
base_attack_min: 16,
base_attack_max: 20,
base_str: 28,
base_agi: 15,
base_int: 22,
str_gain: 2.9,
agi_gain: 1.5,
int_gain: 2.9,
attack_range: 375,
projectile_speed: 900,
attack_rate: 1.7,
move_speed: 290,
turn_rate: 1,
cm_enabled: true,
legs: 2,
pro_win: 37,
pro_pick: 81,
hero_id: 65,
pro_ban: 160,

},
{
id: 66,
name: "chen",
localized_name: "Chen",
primary_attr: "Intelligence",
attack_type: "Ranged",
roles: [
" Support",
" Jungler",
" Pusher"
],
img: "/apps/dota2/images/heroes/chen_full.png?",
icon: "/apps/dota2/images/heroes/chen_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: -1,
base_mr: 25,
base_attack_min: 29,
base_attack_max: 39,
base_str: 25,
base_agi: 15,
base_int: 19,
str_gain: 2,
agi_gain: 2.1,
int_gain: 3.2,
attack_range: 650,
projectile_speed: 1100,
attack_rate: 1.7,
move_speed: 305,
turn_rate: 0.6,
cm_enabled: true,
legs: 2,
pro_win: 68,
pro_pick: 106,
hero_id: 66,
pro_ban: 349,

},
{
id: 67,
name: "spectre",
localized_name: "Spectre",
primary_attr: "Agility",
attack_type: "Melee",
roles: [
" Carry",
" Durable",
" Escape"
],
img: "/apps/dota2/images/heroes/spectre_full.png?",
icon: "/apps/dota2/images/heroes/spectre_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: 0,
base_mr: 25,
base_attack_min: 23,
base_attack_max: 27,
base_str: 23,
base_agi: 23,
base_int: 16,
str_gain: 2.5,
agi_gain: 2.1,
int_gain: 1.9,
attack_range: 150,
projectile_speed: 900,
attack_rate: 1.7,
move_speed: 290,
turn_rate: 0.5,
cm_enabled: true,
legs: 0,
pro_win: 20,
pro_pick: 42,
hero_id: 67,
pro_ban: 43,

},
{
id: 68,
name: "ancient_apparition",
localized_name: "Ancient Apparition",
primary_attr: "Intelligence",
attack_type: "Ranged",
roles: [
" Support",
" Disabler",
" Nuker"
],
img: "/apps/dota2/images/heroes/ancient_apparition_full.png?",
icon: "/apps/dota2/images/heroes/ancient_apparition_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: -1,
base_mr: 25,
base_attack_min: 21,
base_attack_max: 31,
base_str: 20,
base_agi: 20,
base_int: 23,
str_gain: 1.9,
agi_gain: 2.2,
int_gain: 3.4,
attack_range: 675,
projectile_speed: 1250,
attack_rate: 1.7,
move_speed: 290,
turn_rate: 0.6,
cm_enabled: true,
legs: 2,
pro_win: 96,
pro_pick: 201,
hero_id: 68,
pro_ban: 239,

},
{
id: 69,
name: "doom_bringer",
localized_name: "Doom",
primary_attr: "Strength",
attack_type: "Melee",
roles: [
" Carry",
" Disabler",
" Initiator",
" Durable",
" Nuker"
],
img: "/apps/dota2/images/heroes/doom_bringer_full.png?",
icon: "/apps/dota2/images/heroes/doom_bringer_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: -1,
base_mr: 25,
base_attack_min: 27,
base_attack_max: 43,
base_str: 26,
base_agi: 11,
base_int: 15,
str_gain: 4,
agi_gain: 0.9,
int_gain: 2.1,
attack_range: 175,
projectile_speed: 900,
attack_rate: 2,
move_speed: 285,
turn_rate: 0.5,
cm_enabled: true,
legs: 2,
pro_win: 22,
pro_pick: 47,
hero_id: 69,
pro_ban: 57,

},
{
id: 70,
name: "ursa",
localized_name: "Ursa",
primary_attr: "Agility",
attack_type: "Melee",
roles: [
" Carry",
" Jungler",
" Durable",
" Disabler"
],
img: "/apps/dota2/images/heroes/ursa_full.png?",
icon: "/apps/dota2/images/heroes/ursa_icon.png",
base_health: 200,
base_health_regen: 0.5,
base_mana: 75,
base_mana_regen: 0,
base_armor: 2,
base_mr: 25,
base_attack_min: 24,
base_attack_max: 28,
base_str: 24,
base_agi: 18,
base_int: 16,
str_gain: 3.3,
agi_gain: 2.4,
int_gain: 1.5,
attack_range: 150,
projectile_speed: 900,
attack_rate: 1.7,
move_speed: 325,
turn_rate: 0.5,
cm_enabled: true,
legs: 2,
pro_win: 22,
pro_pick: 55,
hero_id: 70,
pro_ban: 80,

},
{
id: 71,
name: "spirit_breaker",
localized_name: "Spirit Breaker",
primary_attr: "Strength",
attack_type: "Melee",
roles: [
" Carry",
" Initiator",
" Disabler",
" Durable",
" Escape"
],
img: "/apps/dota2/images/heroes/spirit_breaker_full.png?",
icon: "/apps/dota2/images/heroes/spirit_breaker_icon.png",
base_health: 200,
base_health_regen: 1.25,
base_mana: 75,
base_mana_regen: 0,
base_armor: 2,
base_mr: 25,
base_attack_min: 31,
base_attack_max: 41,
base_str: 29,
base_agi: 17,
base_int: 14,
str_gain: 3.1,
agi_gain: 1.7,
int_gain: 1.8,
attack_range: 150,
projectile_speed: 900,
attack_rate: 1.9,
move_speed: 285,
turn_rate: 0.5,
cm_enabled: true,
legs: 2,
pro_win: 49,
pro_pick: 117,
hero_id: 71,
pro_ban: 192,

},
{
id: 72,
name: "gyrocopter",
localized_name: "Gyrocopter",
primary_attr: "Agility",
attack_type: "Ranged",
roles: [
" Carry",
" Nuker",
" Disabler"
],
img: "/apps/dota2/images/heroes/gyrocopter_full.png?",
icon: "/apps/dota2/images/heroes/gyrocopter_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: 2,
base_mr: 25,
base_attack_min: 21,
base_attack_max: 31,
base_str: 22,
base_agi: 19,
base_int: 19,
str_gain: 2.3,
agi_gain: 3.6,
int_gain: 2.1,
attack_range: 365,
projectile_speed: 3000,
attack_rate: 1.7,
move_speed: 315,
turn_rate: 0.6,
cm_enabled: true,
legs: 2,
pro_win: 91,
pro_pick: 171,
hero_id: 72,
pro_ban: 113,

},
{
id: 73,
name: "alchemist",
localized_name: "Alchemist",
primary_attr: "Strength",
attack_type: "Melee",
roles: [
" Carry",
" Support",
" Durable",
" Disabler",
" Initiator",
" Nuker"
],
img: "/apps/dota2/images/heroes/alchemist_full.png?",
icon: "/apps/dota2/images/heroes/alchemist_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: -1,
base_mr: 25,
base_attack_min: 24,
base_attack_max: 33,
base_str: 25,
base_agi: 22,
base_int: 25,
str_gain: 2.4,
agi_gain: 1.2,
int_gain: 1.8,
attack_range: 150,
projectile_speed: 900,
attack_rate: 1.7,
move_speed: 305,
turn_rate: 0.6,
cm_enabled: true,
legs: 2,
pro_win: 105,
pro_pick: 165,
hero_id: 73,
pro_ban: 591,

},
{
id: 74,
name: "invoker",
localized_name: "Invoker",
primary_attr: "Intelligence",
attack_type: "Ranged",
roles: [
" Carry",
" Nuker",
" Disabler",
" Escape",
" Pusher"
],
img: "/apps/dota2/images/heroes/invoker_full.png?",
icon: "/apps/dota2/images/heroes/invoker_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: -1,
base_mr: 25,
base_attack_min: 27,
base_attack_max: 33,
base_str: 18,
base_agi: 14,
base_int: 14,
str_gain: 2.4,
agi_gain: 1.9,
int_gain: 4.6,
attack_range: 600,
projectile_speed: 900,
attack_rate: 1.7,
move_speed: 280,
turn_rate: 0.5,
cm_enabled: true,
legs: 2,
pro_win: 86,
pro_pick: 190,
hero_id: 74,
pro_ban: 120,

},
{
id: 75,
name: "silencer",
localized_name: "Silencer",
primary_attr: "Intelligence",
attack_type: "Ranged",
roles: [
" Carry",
" Support",
" Disabler",
" Initiator",
" Nuker"
],
img: "/apps/dota2/images/heroes/silencer_full.png?",
icon: "/apps/dota2/images/heroes/silencer_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: -1,
base_mr: 25,
base_attack_min: 18,
base_attack_max: 32,
base_str: 19,
base_agi: 22,
base_int: 25,
str_gain: 2.7,
agi_gain: 3,
int_gain: 2.9,
attack_range: 600,
projectile_speed: 1000,
attack_rate: 1.7,
move_speed: 290,
turn_rate: 0.6,
cm_enabled: true,
legs: 2,
pro_win: 38,
pro_pick: 77,
hero_id: 75,
pro_ban: 80,

},
{
id: 76,
name: "obsidian_destroyer",
localized_name: "Outworld Devourer",
primary_attr: "Intelligence",
attack_type: "Ranged",
roles: [
" Carry",
" Nuker",
" Disabler"
],
img: "/apps/dota2/images/heroes/obsidian_destroyer_full.png?",
icon: "/apps/dota2/images/heroes/obsidian_destroyer_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: 1.5,
base_mr: 25,
base_attack_min: 16,
base_attack_max: 31,
base_str: 19,
base_agi: 24,
base_int: 28,
str_gain: 2.6,
agi_gain: 2,
int_gain: 3.5,
attack_range: 450,
projectile_speed: 900,
attack_rate: 1.7,
move_speed: 310,
turn_rate: 0.5,
cm_enabled: true,
legs: 4,
pro_win: 75,
pro_pick: 166,
hero_id: 76,
pro_ban: 484,

},
{
id: 77,
name: "lycan",
localized_name: "Lycan",
primary_attr: "Strength",
attack_type: "Melee",
roles: [
" Carry",
" Pusher",
" Jungler",
" Durable",
" Escape"
],
img: "/apps/dota2/images/heroes/lycan_full.png?",
icon: "/apps/dota2/images/heroes/lycan_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: -1,
base_mr: 25,
base_attack_min: 30,
base_attack_max: 35,
base_str: 25,
base_agi: 16,
base_int: 17,
str_gain: 3.4,
agi_gain: 1,
int_gain: 1.4,
attack_range: 150,
projectile_speed: 900,
attack_rate: 1.7,
move_speed: 315,
turn_rate: 0.5,
cm_enabled: true,
legs: 2,
pro_win: 3,
pro_pick: 4,
hero_id: 77,
pro_ban: 10,

},
{
id: 78,
name: "brewmaster",
localized_name: "Brewmaster",
primary_attr: "Strength",
attack_type: "Melee",
roles: [
" Carry",
" Initiator",
" Durable",
" Disabler",
" Nuker"
],
img: "/apps/dota2/images/heroes/brewmaster_full.png?",
icon: "/apps/dota2/images/heroes/brewmaster_icon.png",
base_health: 200,
base_health_regen: 0.5,
base_mana: 75,
base_mana_regen: 0,
base_armor: -2,
base_mr: 25,
base_attack_min: 29,
base_attack_max: 36,
base_str: 23,
base_agi: 22,
base_int: 14,
str_gain: 3.7,
agi_gain: 2,
int_gain: 1.6,
attack_range: 150,
projectile_speed: 900,
attack_rate: 1.7,
move_speed: 305,
turn_rate: 0.6,
cm_enabled: true,
legs: 2,
pro_win: 7,
pro_pick: 28,
hero_id: 78,
pro_ban: 13,

},
{
id: 79,
name: "shadow_demon",
localized_name: "Shadow Demon",
primary_attr: "Intelligence",
attack_type: "Ranged",
roles: [
" Support",
" Disabler",
" Initiator",
" Nuker"
],
img: "/apps/dota2/images/heroes/shadow_demon_full.png?",
icon: "/apps/dota2/images/heroes/shadow_demon_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: 0,
base_mr: 25,
base_attack_min: 29,
base_attack_max: 33,
base_str: 23,
base_agi: 18,
base_int: 21,
str_gain: 2.6,
agi_gain: 2.2,
int_gain: 3.3,
attack_range: 500,
projectile_speed: 900,
attack_rate: 1.7,
move_speed: 290,
turn_rate: 0.6,
cm_enabled: true,
legs: 2,
pro_win: 162,
pro_pick: 286,
hero_id: 79,
pro_ban: 478,

},
{
id: 80,
name: "lone_druid",
localized_name: "Lone Druid",
primary_attr: "Agility",
attack_type: "Ranged",
roles: [
" Carry",
" Pusher",
" Jungler",
" Durable"
],
img: "/apps/dota2/images/heroes/lone_druid_full.png?",
icon: "/apps/dota2/images/heroes/lone_druid_icon.png",
base_health: 200,
base_health_regen: 0.25,
base_mana: 75,
base_mana_regen: 0,
base_armor: -2,
base_mr: 25,
base_attack_min: 18,
base_attack_max: 22,
base_str: 18,
base_agi: 20,
base_int: 13,
str_gain: 2.7,
agi_gain: 2.8,
int_gain: 1.4,
attack_range: 550,
projectile_speed: 900,
attack_rate: 1.7,
move_speed: 325,
turn_rate: 0.5,
cm_enabled: true,
legs: 2,
pro_win: 3,
pro_pick: 13,
hero_id: 80,
pro_ban: 22,

},
{
id: 81,
name: "chaos_knight",
localized_name: "Chaos Knight",
primary_attr: "Strength",
attack_type: "Melee",
roles: [
" Carry",
" Disabler",
" Durable",
" Pusher",
" Initiator"
],
img: "/apps/dota2/images/heroes/chaos_knight_full.png?",
icon: "/apps/dota2/images/heroes/chaos_knight_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: 1,
base_mr: 25,
base_attack_min: 29,
base_attack_max: 59,
base_str: 22,
base_agi: 14,
base_int: 18,
str_gain: 3.4,
agi_gain: 2.1,
int_gain: 1.2,
attack_range: 150,
projectile_speed: 900,
attack_rate: 1.7,
move_speed: 320,
turn_rate: 0.5,
cm_enabled: true,
legs: 2,
pro_win: 12,
pro_pick: 29,
hero_id: 81,
pro_ban: 8,

},
{
id: 82,
name: "meepo",
localized_name: "Meepo",
primary_attr: "Agility",
attack_type: "Melee",
roles: [
" Carry",
" Escape",
" Nuker",
" Disabler",
" Initiator",
" Pusher"
],
img: "/apps/dota2/images/heroes/meepo_full.png?",
icon: "/apps/dota2/images/heroes/meepo_icon.png",
base_health: 200,
base_health_regen: 0.25,
base_mana: 75,
base_mana_regen: 0,
base_armor: 3,
base_mr: 25,
base_attack_min: 22,
base_attack_max: 28,
base_str: 24,
base_agi: 24,
base_int: 20,
str_gain: 1.8,
agi_gain: 1.8,
int_gain: 1.6,
attack_range: 150,
projectile_speed: 900,
attack_rate: 1.7,
move_speed: 330,
turn_rate: 0.65,
cm_enabled: true,
legs: 2,
pro_win: 26,
pro_pick: 40,
hero_id: 82,
pro_ban: 108,

},
{
id: 83,
name: "treant",
localized_name: "Treant Protector",
primary_attr: "Strength",
attack_type: "Melee",
roles: [
" Support",
" Initiator",
" Durable",
" Disabler",
" Escape"
],
img: "/apps/dota2/images/heroes/treant_full.png?",
icon: "/apps/dota2/images/heroes/treant_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0.5,
base_armor: -2,
base_mr: 25,
base_attack_min: 62,
base_attack_max: 70,
base_str: 25,
base_agi: 15,
base_int: 20,
str_gain: 4.1,
agi_gain: 2,
int_gain: 1.8,
attack_range: 150,
projectile_speed: 900,
attack_rate: 1.9,
move_speed: 270,
turn_rate: 0.5,
cm_enabled: true,
legs: 2,
pro_win: 41,
pro_pick: 68,
hero_id: 83,
pro_ban: 180,

},
{
id: 84,
name: "ogre_magi",
localized_name: "Ogre Magi",
primary_attr: "Intelligence",
attack_type: "Melee",
roles: [
" Support",
" Nuker",
" Disabler",
" Durable",
" Initiator"
],
img: "/apps/dota2/images/heroes/ogre_magi_full.png?",
icon: "/apps/dota2/images/heroes/ogre_magi_icon.png",
base_health: 200,
base_health_regen: 3.25,
base_mana: 75,
base_mana_regen: 0,
base_armor: 6,
base_mr: 25,
base_attack_min: 43,
base_attack_max: 49,
base_str: 25,
base_agi: 14,
base_int: 15,
str_gain: 3.5,
agi_gain: 1.6,
int_gain: 2.3,
attack_range: 150,
projectile_speed: 900,
attack_rate: 1.7,
move_speed: 290,
turn_rate: 0.6,
cm_enabled: true,
legs: 2,
pro_win: 191,
pro_pick: 386,
hero_id: 84,
pro_ban: 421,

},
{
id: 85,
name: "undying",
localized_name: "Undying",
primary_attr: "Strength",
attack_type: "Melee",
roles: [
" Support",
" Durable",
" Disabler",
" Nuker"
],
img: "/apps/dota2/images/heroes/undying_full.png?",
icon: "/apps/dota2/images/heroes/undying_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: 2,
base_mr: 25,
base_attack_min: 35,
base_attack_max: 43,
base_str: 22,
base_agi: 10,
base_int: 27,
str_gain: 2.8,
agi_gain: 0.8,
int_gain: 2.8,
attack_range: 150,
projectile_speed: 900,
attack_rate: 1.7,
move_speed: 300,
turn_rate: 0.6,
cm_enabled: true,
legs: 2,
pro_win: 30,
pro_pick: 57,
hero_id: 85,
pro_ban: 74,

},
{
id: 86,
name: "rubick",
localized_name: "Rubick",
primary_attr: "Intelligence",
attack_type: "Ranged",
roles: [
" Support",
" Disabler",
" Nuker"
],
img: "/apps/dota2/images/heroes/rubick_full.png?",
icon: "/apps/dota2/images/heroes/rubick_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: -1,
base_mr: 25,
base_attack_min: 22,
base_attack_max: 32,
base_str: 21,
base_agi: 19,
base_int: 25,
str_gain: 2,
agi_gain: 2.1,
int_gain: 3.1,
attack_range: 550,
projectile_speed: 1125,
attack_rate: 1.7,
move_speed: 290,
turn_rate: 0.7,
cm_enabled: true,
legs: 2,
pro_win: 162,
pro_pick: 309,
hero_id: 86,
pro_ban: 166,

},
{
id: 87,
name: "disruptor",
localized_name: "Disruptor",
primary_attr: "Intelligence",
attack_type: "Ranged",
roles: [
" Support",
" Disabler",
" Nuker",
" Initiator"
],
img: "/apps/dota2/images/heroes/disruptor_full.png?",
icon: "/apps/dota2/images/heroes/disruptor_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: 0,
base_mr: 25,
base_attack_min: 29,
base_attack_max: 33,
base_str: 21,
base_agi: 15,
base_int: 20,
str_gain: 2.4,
agi_gain: 1.4,
int_gain: 2.9,
attack_range: 600,
projectile_speed: 1200,
attack_rate: 1.7,
move_speed: 295,
turn_rate: 0.5,
cm_enabled: true,
legs: 2,
pro_win: 18,
pro_pick: 44,
hero_id: 87,
pro_ban: 4,

},
{
id: 88,
name: "nyx_assassin",
localized_name: "Nyx Assassin",
primary_attr: "Agility",
attack_type: "Melee",
roles: [
" Disabler",
" Nuker",
" Initiator",
" Escape"
],
img: "/apps/dota2/images/heroes/nyx_assassin_full.png?",
icon: "/apps/dota2/images/heroes/nyx_assassin_icon.png",
base_health: 200,
base_health_regen: 3.25,
base_mana: 75,
base_mana_regen: 0,
base_armor: 1,
base_mr: 25,
base_attack_min: 27,
base_attack_max: 31,
base_str: 18,
base_agi: 19,
base_int: 18,
str_gain: 2.5,
agi_gain: 2.5,
int_gain: 2.1,
attack_range: 150,
projectile_speed: 900,
attack_rate: 1.7,
move_speed: 305,
turn_rate: 0.5,
cm_enabled: true,
legs: 6,
pro_win: 33,
pro_pick: 61,
hero_id: 88,
pro_ban: 101,
},
{
id: 89,
name: "naga_siren",
localized_name: "Naga Siren",
primary_attr: "Agility",
attack_type: "Melee",
roles: [
" Carry",
" Support",
" Pusher",
" Disabler",
" Initiator",
" Escape"
],
img: "/apps/dota2/images/heroes/naga_siren_full.png?",
icon: "/apps/dota2/images/heroes/naga_siren_icon.png",
base_health: 200,
base_health_regen: 1.5,
base_mana: 75,
base_mana_regen: 0,
base_armor: 3,
base_mr: 25,
base_attack_min: 23,
base_attack_max: 25,
base_str: 22,
base_agi: 21,
base_int: 21,
str_gain: 2.8,
agi_gain: 3.7,
int_gain: 2,
attack_range: 150,
projectile_speed: 900,
attack_rate: 1.7,
move_speed: 320,
turn_rate: 0.5,
cm_enabled: true,
legs: 0,
pro_win: 41,
pro_pick: 71,
hero_id: 89,
pro_ban: 206,

},
{
id: 90,
name: "keeper_of_the_light",
localized_name: "Keeper of the Light",
primary_attr: "Intelligence",
attack_type: "Ranged",
roles: [
" Support",
" Nuker",
" Disabler",
" Jungler"
],
img: "/apps/dota2/images/heroes/keeper_of_the_light_full.png?",
icon: "/apps/dota2/images/heroes/keeper_of_the_light_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: -1,
base_mr: 25,
base_attack_min: 20,
base_attack_max: 27,
base_str: 16,
base_agi: 15,
base_int: 23,
str_gain: 2.3,
agi_gain: 1.6,
int_gain: 3.2,
attack_range: 600,
projectile_speed: 900,
attack_rate: 1.7,
move_speed: 330,
turn_rate: 0.5,
cm_enabled: true,
legs: 2,
pro_win: 8,
pro_pick: 18,
hero_id: 90,
pro_ban: 14,

},
{
id: 91,
name: "wisp",
localized_name: "Io",
primary_attr: "Strength",
attack_type: "Ranged",
roles: [
" Support",
" Escape",
" Nuker"
],
img: "/apps/dota2/images/heroes/wisp_full.png?",
icon: "/apps/dota2/images/heroes/wisp_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: -2,
base_mr: 25,
base_attack_min: 22,
base_attack_max: 31,
base_str: 17,
base_agi: 14,
base_int: 23,
str_gain: 2.5,
agi_gain: 1.6,
int_gain: 1.7,
attack_range: 575,
projectile_speed: 1200,
attack_rate: 1.7,
move_speed: 280,
turn_rate: 0.7,
cm_enabled: true,
legs: 0,
pro_win: 39,
pro_pick: 70,
hero_id: 91,
pro_ban: 326,

},
{
id: 92,
name: "visage",
localized_name: "Visage",
primary_attr: "Intelligence",
attack_type: "Ranged",
roles: [
" Support",
" Nuker",
" Durable",
" Disabler",
" Pusher"
],
img: "/apps/dota2/images/heroes/visage_full.png?",
icon: "/apps/dota2/images/heroes/visage_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: -2,
base_mr: 25,
base_attack_min: 23,
base_attack_max: 33,
base_str: 22,
base_agi: 11,
base_int: 22,
str_gain: 2.8,
agi_gain: 1.3,
int_gain: 2.9,
attack_range: 600,
projectile_speed: 900,
attack_rate: 1.7,
move_speed: 285,
turn_rate: 0.5,
cm_enabled: true,
legs: 2,
pro_win: 11,
pro_pick: 18,
hero_id: 92,
pro_ban: 15,

},
{
id: 93,
name: "slark",
localized_name: "Slark",
primary_attr: "Agility",
attack_type: "Melee",
roles: [
" Carry",
" Escape",
" Disabler",
" Nuker"
],
img: "/apps/dota2/images/heroes/slark_full.png?",
icon: "/apps/dota2/images/heroes/slark_icon.png",
base_health: 200,
base_health_regen: 1.75,
base_mana: 75,
base_mana_regen: 0,
base_armor: 0,
base_mr: 25,
base_attack_min: 33,
base_attack_max: 41,
base_str: 21,
base_agi: 21,
base_int: 16,
str_gain: 1.9,
agi_gain: 1.7,
int_gain: 1.7,
attack_range: 150,
projectile_speed: 0,
attack_rate: 1.7,
move_speed: 300,
turn_rate: 0.7,
cm_enabled: true,
legs: 2,
pro_win: 99,
pro_pick: 183,
hero_id: 93,
pro_ban: 378,

},
{
id: 94,
name: "medusa",
localized_name: "Medusa",
primary_attr: "Agility",
attack_type: "Ranged",
roles: [
" Carry",
" Disabler",
" Durable"
],
img: "/apps/dota2/images/heroes/medusa_full.png?",
icon: "/apps/dota2/images/heroes/medusa_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: -1,
base_mr: 25,
base_attack_min: 24,
base_attack_max: 30,
base_str: 15,
base_agi: 22,
base_int: 19,
str_gain: 1.3,
agi_gain: 3.6,
int_gain: 2.6,
attack_range: 600,
projectile_speed: 1200,
attack_rate: 1.7,
move_speed: 275,
turn_rate: 0.5,
cm_enabled: true,
legs: 0,
pro_win: 10,
pro_pick: 33,
hero_id: 94,
pro_ban: 43,

},
{
id: 95,
name: "troll_warlord",
localized_name: "Troll Warlord",
primary_attr: "Agility",
attack_type: "Ranged",
roles: [
" Carry",
" Pusher",
" Disabler",
" Durable"
],
img: "/apps/dota2/images/heroes/troll_warlord_full.png?",
icon: "/apps/dota2/images/heroes/troll_warlord_icon.png",
base_health: 200,
base_health_regen: 0.25,
base_mana: 75,
base_mana_regen: 0,
base_armor: -1,
base_mr: 25,
base_attack_min: 23,
base_attack_max: 35,
base_str: 21,
base_agi: 21,
base_int: 13,
str_gain: 2.5,
agi_gain: 2.9,
int_gain: 1,
attack_range: 500,
projectile_speed: 1200,
attack_rate: 1.7,
move_speed: 290,
turn_rate: 0.5,
cm_enabled: true,
legs: 2,
pro_win: 67,
pro_pick: 138,
hero_id: 95,
pro_ban: 118,

},
{
id: 96,
name: "centaur",
localized_name: "Centaur Warrunner",
primary_attr: "Strength",
attack_type: "Melee",
roles: [
" Durable",
" Initiator",
" Disabler",
" Nuker",
" Escape"
],
img: "/apps/dota2/images/heroes/centaur_full.png?",
icon: "/apps/dota2/images/heroes/centaur_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: 0,
base_mr: 25,
base_attack_min: 36,
base_attack_max: 38,
base_str: 27,
base_agi: 15,
base_int: 15,
str_gain: 4.6,
agi_gain: 1,
int_gain: 1.6,
attack_range: 150,
projectile_speed: 900,
attack_rate: 1.7,
move_speed: 300,
turn_rate: 0.5,
cm_enabled: true,
legs: 4,
pro_win: 102,
pro_pick: 192,
hero_id: 96,
pro_ban: 222,

},
{
id: 97,
name: "magnataur",
localized_name: "Magnus",
primary_attr: "Strength",
attack_type: "Melee",
roles: [
" Initiator",
" Disabler",
" Nuker",
" Escape"
],
img: "/apps/dota2/images/heroes/magnataur_full.png?",
icon: "/apps/dota2/images/heroes/magnataur_icon.png",
base_health: 200,
base_health_regen: 0.5,
base_mana: 75,
base_mana_regen: 0,
base_armor: 1,
base_mr: 25,
base_attack_min: 32,
base_attack_max: 44,
base_str: 25,
base_agi: 15,
base_int: 19,
str_gain: 3.5,
agi_gain: 2.5,
int_gain: 1.7,
attack_range: 150,
projectile_speed: 900,
attack_rate: 1.8,
move_speed: 305,
turn_rate: 0.8,
cm_enabled: true,
legs: 4,
pro_win: 72,
pro_pick: 124,
hero_id: 97,
pro_ban: 226,

},
{
id: 98,
name: "shredder",
localized_name: "Timbersaw",
primary_attr: "Strength",
attack_type: "Melee",
roles: [
" Nuker",
" Durable",
" Escape"
],
img: "/apps/dota2/images/heroes/shredder_full.png?",
icon: "/apps/dota2/images/heroes/shredder_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: -1,
base_mr: 25,
base_attack_min: 26,
base_attack_max: 30,
base_str: 21,
base_agi: 16,
base_int: 23,
str_gain: 3.2,
agi_gain: 1.3,
int_gain: 2.7,
attack_range: 150,
projectile_speed: 900,
attack_rate: 1.7,
move_speed: 290,
turn_rate: 0.6,
cm_enabled: true,
legs: 2,
pro_win: 55,
pro_pick: 108,
hero_id: 98,
pro_ban: 121,

},
{
id: 99,
name: "bristleback",
localized_name: "Bristleback",
primary_attr: "Strength",
attack_type: "Melee",
roles: [
" Carry",
" Durable",
" Initiator",
" Nuker"
],
img: "/apps/dota2/images/heroes/bristleback_full.png?",
icon: "/apps/dota2/images/heroes/bristleback_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: 1,
base_mr: 25,
base_attack_min: 22,
base_attack_max: 32,
base_str: 22,
base_agi: 17,
base_int: 14,
str_gain: 2.9,
agi_gain: 1.8,
int_gain: 2.8,
attack_range: 150,
projectile_speed: 900,
attack_rate: 1.8,
move_speed: 290,
turn_rate: 1,
cm_enabled: true,
legs: 2,
pro_win: 67,
pro_pick: 141,
hero_id: 99,
pro_ban: 159,

},
{
id: 100,
name: "tusk",
localized_name: "Tusk",
primary_attr: "Strength",
attack_type: "Melee",
roles: [
" Initiator",
" Disabler",
" Nuker"
],
img: "/apps/dota2/images/heroes/tusk_full.png?",
icon: "/apps/dota2/images/heroes/tusk_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: -1,
base_mr: 25,
base_attack_min: 27,
base_attack_max: 31,
base_str: 23,
base_agi: 23,
base_int: 18,
str_gain: 3.9,
agi_gain: 2.1,
int_gain: 1.7,
attack_range: 150,
projectile_speed: 900,
attack_rate: 1.7,
move_speed: 300,
turn_rate: 0.7,
cm_enabled: true,
legs: 2,
pro_win: 33,
pro_pick: 71,
hero_id: 100,
pro_ban: 25,

},
{
id: 101,
name: "skywrath_mage",
localized_name: "Skywrath Mage",
primary_attr: "Intelligence",
attack_type: "Ranged",
roles: [
" Support",
" Nuker",
" Disabler"
],
img: "/apps/dota2/images/heroes/skywrath_mage_full.png?",
icon: "/apps/dota2/images/heroes/skywrath_mage_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: -2,
base_mr: 25,
base_attack_min: 14,
base_attack_max: 24,
base_str: 21,
base_agi: 13,
base_int: 25,
str_gain: 2,
agi_gain: 0.8,
int_gain: 4.1,
attack_range: 600,
projectile_speed: 1000,
attack_rate: 1.7,
move_speed: 325,
turn_rate: 0.5,
cm_enabled: true,
legs: 2,
pro_win: 27,
pro_pick: 70,
hero_id: 101,
pro_ban: 27,

},
{
id: 102,
name: "abaddon",
localized_name: "Abaddon",
primary_attr: "Strength",
attack_type: "Melee",
roles: [
" Support",
" Carry",
" Durable"
],
img: "/apps/dota2/images/heroes/abaddon_full.png?",
icon: "/apps/dota2/images/heroes/abaddon_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: -2,
base_mr: 25,
base_attack_min: 32,
base_attack_max: 42,
base_str: 23,
base_agi: 23,
base_int: 21,
str_gain: 3,
agi_gain: 1.5,
int_gain: 2,
attack_range: 150,
projectile_speed: 900,
attack_rate: 1.7,
move_speed: 325,
turn_rate: 0.5,
cm_enabled: true,
legs: 2,
pro_win: 50,
pro_pick: 93,
hero_id: 102,
pro_ban: 51,

},
{
id: 103,
name: "elder_titan",
localized_name: "Elder Titan",
primary_attr: "Strength",
attack_type: "Melee",
roles: [
" Initiator",
" Disabler",
" Nuker",
" Durable"
],
img: "/apps/dota2/images/heroes/elder_titan_full.png?",
icon: "/apps/dota2/images/heroes/elder_titan_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: 0,
base_mr: 25,
base_attack_min: 23,
base_attack_max: 33,
base_str: 24,
base_agi: 14,
base_int: 23,
str_gain: 3,
agi_gain: 1.8,
int_gain: 1.6,
attack_range: 150,
projectile_speed: 900,
attack_rate: 1.7,
move_speed: 310,
turn_rate: 0.5,
cm_enabled: true,
legs: 2,
pro_win: 102,
pro_pick: 192,
hero_id: 103,
pro_ban: 165,

},
{
id: 104,
name: "legion_commander",
localized_name: "Legion Commander",
primary_attr: "Strength",
attack_type: "Melee",
roles: [
" Carry",
" Disabler",
" Initiator",
" Durable",
" Nuker"
],
img: "/apps/dota2/images/heroes/legion_commander_full.png?",
icon: "/apps/dota2/images/heroes/legion_commander_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: 0,
base_mr: 25,
base_attack_min: 35,
base_attack_max: 39,
base_str: 26,
base_agi: 18,
base_int: 20,
str_gain: 3.3,
agi_gain: 1.7,
int_gain: 2.2,
attack_range: 150,
projectile_speed: 900,
attack_rate: 1.7,
move_speed: 330,
turn_rate: 0.5,
cm_enabled: true,
legs: 2,
pro_win: 48,
pro_pick: 91,
hero_id: 104,
pro_ban: 61,

},
{
id: 105,
name: "techies",
localized_name: "Techies",
primary_attr: "Intelligence",
attack_type: "Ranged",
roles: [
" Nuker",
" Disabler"
],
img: "/apps/dota2/images/heroes/techies_full.png?",
icon: "/apps/dota2/images/heroes/techies_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 1,
base_armor: 5,
base_mr: 25,
base_attack_min: 9,
base_attack_max: 11,
base_str: 19,
base_agi: 14,
base_int: 22,
str_gain: 2.5,
agi_gain: 1.3,
int_gain: 3.3,
attack_range: 700,
projectile_speed: 900,
attack_rate: 1.7,
move_speed: 310,
turn_rate: 0.5,
cm_enabled: true,
legs: 6,
pro_win: 10,
pro_pick: 14,
hero_id: 105,
pro_ban: 29,

},
{
id: 106,
name: "ember_spirit",
localized_name: "Ember Spirit",
primary_attr: "Agility",
attack_type: "Melee",
roles: [
" Carry",
" Escape",
" Nuker",
" Disabler",
" Initiator"
],
img: "/apps/dota2/images/heroes/ember_spirit_full.png?",
icon: "/apps/dota2/images/heroes/ember_spirit_icon.png",
base_health: 200,
base_health_regen: 0.5,
base_mana: 75,
base_mana_regen: 0,
base_armor: 0,
base_mr: 25,
base_attack_min: 33,
base_attack_max: 37,
base_str: 21,
base_agi: 22,
base_int: 20,
str_gain: 2.6,
agi_gain: 2.1,
int_gain: 1.8,
attack_range: 150,
projectile_speed: 900,
attack_rate: 1.7,
move_speed: 305,
turn_rate: 0.5,
cm_enabled: true,
legs: 2,
pro_win: 136,
pro_pick: 284,
hero_id: 106,
pro_ban: 386,

},
{
id: 107,
name: "earth_spirit",
localized_name: "Earth Spirit",
primary_attr: "Strength",
attack_type: "Melee",
roles: [
" Nuker",
" Escape",
" Disabler",
" Initiator",
" Durable"
],
img: "/apps/dota2/images/heroes/earth_spirit_full.png?",
icon: "/apps/dota2/images/heroes/earth_spirit_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: 0,
base_mr: 25,
base_attack_min: 25,
base_attack_max: 35,
base_str: 21,
base_agi: 17,
base_int: 18,
str_gain: 4.4,
agi_gain: 1.5,
int_gain: 2.1,
attack_range: 150,
projectile_speed: 900,
attack_rate: 1.7,
move_speed: 290,
turn_rate: 0.6,
cm_enabled: true,
legs: 2,
pro_win: 51,
pro_pick: 95,
hero_id: 107,
pro_ban: 47,

},
{
id: 108,
name: "abyssal_underlord",
localized_name: "Underlord",
primary_attr: "Strength",
attack_type: "Melee",
roles: [
" Support",
" Nuker",
" Disabler",
" Durable",
" Escape"
],
img: "/apps/dota2/images/heroes/abyssal_underlord_full.png?",
icon: "/apps/dota2/images/heroes/abyssal_underlord_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: 1,
base_mr: 25,
base_attack_min: 37,
base_attack_max: 43,
base_str: 25,
base_agi: 12,
base_int: 17,
str_gain: 3.3,
agi_gain: 1.3,
int_gain: 2.3,
attack_range: 150,
projectile_speed: 900,
attack_rate: 1.7,
move_speed: 295,
turn_rate: 0.6,
cm_enabled: true,
legs: 2,
pro_win: 14,
pro_pick: 36,
hero_id: 108,
pro_ban: 10,

},
{
id: 109,
name: "terrorblade",
localized_name: "Terrorblade",
primary_attr: "Agility",
attack_type: "Melee",
roles: [
" Carry",
" Pusher",
" Nuker"
],
img: "/apps/dota2/images/heroes/terrorblade_full.png?",
icon: "/apps/dota2/images/heroes/terrorblade_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: 7,
base_mr: 25,
base_attack_min: 26,
base_attack_max: 32,
base_str: 15,
base_agi: 22,
base_int: 19,
str_gain: 1.5,
agi_gain: 4.8,
int_gain: 1.6,
attack_range: 150,
projectile_speed: 900,
attack_rate: 1.5,
move_speed: 310,
turn_rate: 0.5,
cm_enabled: true,
legs: 2,
pro_win: 9,
pro_pick: 24,
hero_id: 109,
pro_ban: 19,

},
{
id: 110,
name: "phoenix",
localized_name: "Phoenix",
primary_attr: "Strength",
attack_type: "Ranged",
roles: [
" Support",
" Nuker",
" Initiator",
" Escape",
" Disabler"
],
img: "/apps/dota2/images/heroes/phoenix_full.png?",
icon: "/apps/dota2/images/heroes/phoenix_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: -2,
base_mr: 25,
base_attack_min: 26,
base_attack_max: 36,
base_str: 21,
base_agi: 12,
base_int: 18,
str_gain: 3.7,
agi_gain: 1.3,
int_gain: 1.8,
attack_range: 500,
projectile_speed: 1100,
attack_rate: 1.7,
move_speed: 280,
turn_rate: 1,
cm_enabled: true,
legs: 2,
pro_win: 28,
pro_pick: 52,
hero_id: 110,
pro_ban: 25,

},
{
id: 111,
name: "oracle",
localized_name: "Oracle",
primary_attr: "Intelligence",
attack_type: "Ranged",
roles: [
" Support",
" Nuker",
" Disabler",
" Escape"
],
img: "/apps/dota2/images/heroes/oracle_full.png?",
icon: "/apps/dota2/images/heroes/oracle_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: 0,
base_mr: 25,
base_attack_min: 18,
base_attack_max: 24,
base_str: 20,
base_agi: 15,
base_int: 21,
str_gain: 2.4,
agi_gain: 1.7,
int_gain: 4,
attack_range: 620,
projectile_speed: 900,
attack_rate: 1.7,
move_speed: 300,
turn_rate: 0.7,
cm_enabled: true,
legs: 2,
pro_win: 56,
pro_pick: 120,
hero_id: 111,
pro_ban: 157,

},
{
id: 112,
name: "winter_wyvern",
localized_name: "Winter Wyvern",
primary_attr: "Intelligence",
attack_type: "Ranged",
roles: [
" Support",
" Disabler",
" Nuker"
],
img: "/apps/dota2/images/heroes/winter_wyvern_full.png?",
icon: "/apps/dota2/images/heroes/winter_wyvern_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: -1,
base_mr: 25,
base_attack_min: 12,
base_attack_max: 19,
base_str: 26,
base_agi: 16,
base_int: 26,
str_gain: 2.6,
agi_gain: 1.9,
int_gain: 3.6,
attack_range: 425,
projectile_speed: 700,
attack_rate: 1.7,
move_speed: 285,
turn_rate: 0.5,
cm_enabled: true,
legs: 2,
pro_win: 26,
pro_pick: 65,
hero_id: 112,
pro_ban: 46,

},
{
id: 113,
name: "arc_warden",
localized_name: "Arc Warden",
primary_attr: "Agility",
attack_type: "Ranged",
roles: [
" Carry",
" Escape",
" Nuker"
],
img: "/apps/dota2/images/heroes/arc_warden_full.png?",
icon: "/apps/dota2/images/heroes/arc_warden_icon.png",
base_health: 200,
base_health_regen: 0.25,
base_mana: 75,
base_mana_regen: 0,
base_armor: -2,
base_mr: 25,
base_attack_min: 31,
base_attack_max: 41,
base_str: 25,
base_agi: 15,
base_int: 24,
str_gain: 3,
agi_gain: 2.4,
int_gain: 2.6,
attack_range: 625,
projectile_speed: 900,
attack_rate: 1.7,
move_speed: 280,
turn_rate: 0.7,
cm_enabled: true,
legs: 2,
pro_win: 22,
pro_pick: 46,
hero_id: 113,
pro_ban: 51,

},
{
id: 114,
name: "monkey_king",
localized_name: "Monkey King",
primary_attr: "Agility",
attack_type: "Melee",
roles: [
" Carry",
" Escape",
" Disabler",
" Initiator"
],
img: "/apps/dota2/images/heroes/monkey_king_full.png?",
icon: "/apps/dota2/images/heroes/monkey_king_icon.png",
base_health: 200,
base_health_regen: 1.5,
base_mana: 75,
base_mana_regen: 0,
base_armor: -3,
base_mr: 25,
base_attack_min: 29,
base_attack_max: 35,
base_str: 19,
base_agi: 22,
base_int: 20,
str_gain: 2.8,
agi_gain: 3.7,
int_gain: 1.8,
attack_range: 300,
projectile_speed: 900,
attack_rate: 1.7,
move_speed: 305,
turn_rate: 0.6,
cm_enabled: true,
legs: 2,
pro_win: 48,
pro_pick: 105,
hero_id: 114,
pro_ban: 111,

},
{
id: 119,
name: "dark_willow",
localized_name: "Dark Willow",
primary_attr: "Intelligence",
attack_type: "Ranged",
roles: [
" Support",
" Nuker",
" Disabler",
" Escape"
],
img: "/apps/dota2/images/heroes/dark_willow_full.png?",
icon: "/apps/dota2/images/heroes/dark_willow_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: -1,
base_mr: 25,
base_attack_min: 27,
base_attack_max: 35,
base_str: 20,
base_agi: 18,
base_int: 18,
str_gain: 2,
agi_gain: 1.6,
int_gain: 3.5,
attack_range: 475,
projectile_speed: 1200,
attack_rate: 1.3,
move_speed: 290,
turn_rate: 0.7,
cm_enabled: true,
legs: 2,
pro_win: 42,
pro_pick: 87,
hero_id: 119,
pro_ban: 61,

},
{
id: 120,
name: "pangolier",
localized_name: "Pangolier",
primary_attr: "Agility",
attack_type: "Melee",
roles: [
" Carry",
" Nuker",
" Disabler",
" Durable",
" Escape",
" Initiator"
],
img: "/apps/dota2/images/heroes/pangolier_full.png?",
icon: "/apps/dota2/images/heroes/pangolier_icon.png",
base_health: 200,
base_health_regen: 0.25,
base_mana: 75,
base_mana_regen: 0,
base_armor: 1,
base_mr: 25,
base_attack_min: 33,
base_attack_max: 39,
base_str: 17,
base_agi: 18,
base_int: 16,
str_gain: 2.5,
agi_gain: 3.2,
int_gain: 1.9,
attack_range: 150,
projectile_speed: 900,
attack_rate: 1.7,
move_speed: 305,
turn_rate: 1,
cm_enabled: true,
legs: 2,
pro_win: 34,
pro_pick: 73,
hero_id: 120,
pro_ban: 43,

},
{
id: 121,
name: "grimstroke",
localized_name: "Grimstroke",
primary_attr: "Intelligence",
attack_type: "Ranged",
roles: [
" Support",
" Nuker",
" Disabler",
" Escape"
],
img: "/apps/dota2/images/heroes/grimstroke_full.png?",
icon: "/apps/dota2/images/heroes/grimstroke_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: 0,
base_mr: 25,
base_attack_min: 27,
base_attack_max: 31,
base_str: 21,
base_agi: 18,
base_int: 23,
str_gain: 2.4,
agi_gain: 1.9,
int_gain: 3.8,
attack_range: 550,
projectile_speed: 900,
attack_rate: 1.7,
move_speed: 290,
turn_rate: 0.6,
cm_enabled: true,
legs: 2,
pro_win: 130,
pro_pick: 276,
hero_id: 121,
pro_ban: 204,

},
{
id: 129,
name: "mars",
localized_name: "Mars",
primary_attr: "Strength",
attack_type: "Melee",
roles: [
" Carry",
" Initiator",
" Disabler",
" Durable"
],
img: "/apps/dota2/images/heroes/mars_full.png?",
icon: "/apps/dota2/images/heroes/mars_icon.png",
base_health: 200,
base_health_regen: null,
base_mana: 75,
base_mana_regen: 0,
base_armor: -1,
base_mr: 25,
base_attack_min: 31,
base_attack_max: 39,
base_str: 23,
base_agi: 20,
base_int: 17,
str_gain: 3.2,
agi_gain: 1.9,
int_gain: 1.4,
attack_range: 250,
projectile_speed: 900,
attack_rate: 1.8,
move_speed: 310,
turn_rate: 0.8,
cm_enabled: true,
legs: 2,
pro_win: 58,
pro_pick: 107,
hero_id: 129,
pro_ban: 129,

}
]